[package]
name = "perlinnoisev2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.2"
rand = "0.8.5"
nalgebra = "0.31.0"
lerp = "0.4.0"
rand_seeder = "0.2.3"
rand_pcg = "0.3.1"
